### PR TITLE
Move contributors badge to the top

### PR DESCRIPTION
**Pull request by szepeviktor**
so it becomes useful

### CODE REVIEW

**Comment by szepeviktor** [comment]
Very BIG problem: https://github.com/all-contributors/all-contributors/issues/361

**Comment by szepeviktor** [comment]
@zauan Done 🍏 

kép

Isn't is neat?

**Comment by zauan** [comment]
Looks better. I am looking in better alternatives for the all contributors app. One example would be https://github.com/sourcerer-io/hall-of-fame

**Comment by szepeviktor** [comment]
The all contributors team did not seem to be professional.

**Pull request merged**
