### PR TITLE
Run PHPStan in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
On level 4 for now.

### CODE REVIEW

**Comment by zauan** [comment]
Hi,

Thank you for your commit. At the moment, I cannot approve this pull request as there are 383 errors that are generated at level 4. Until I resolve all of these problems, all pull requests will fail the automatic checks.

**Comment by szepeviktor** [comment]
Okay.

We are in a much better shape than before!

**Comment by szepeviktor** [comment]
Now at 77!!

**Comment by szepeviktor** [comment]
Under 50.

Now it's your turn :)

**Comment by szepeviktor** [comment]
Very nice progress :)
PHPStan's benefit (mainly) comes on higher levels.

> From: Balasa Sorin Stefan <stefan@hogash.com>

BTW your git client is not configured with your GitHub account.

**Comment by szepeviktor** [comment]
I've messed up array shapes in two places: it is not a flat array but an array in array :)

You may put constants in `tests/phpstan/bootstrap.php` and include them in `autoload_files:`

**Comment by szepeviktor** [comment]
...but basically using core's CONSTANTS is not the best idea - there are core functions to read _some_ of them

**Comment by zauan** [comment]
yeah... I've used some legacy code from our Kallyas theme and find;t searched if an alternative can be used... I want to be as compatible with WP standards as I can so I will look for alternatives now.

By the way, is there any way we can get in touch?

**Comment by szepeviktor** [comment]
Yes

- tel:0036-20-4242498
- mailto:viktor@szepe.net
- and you've been invited to my Slack

**Comment by szepeviktor** [comment]
I'd like to create a Value Object for "option schema"?
It there documentation on this?

**Comment by szepeviktor** [comment]
@zauan Done 🍏

**Comment by zauan** [comment]
I've made some changes and fixed all warnings up until level 5 (which I've set as default)

Also, I've approved your pull request!

Thank you for your help.

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
