### PR TITLE
Mitigate always changing line numbers

### PR DESCRIPTION
**Pull request by szepeviktor**
When you insert a new line into a php file containing translations
line numbers will change :(

### CODE REVIEW

**Comment by szepeviktor** [comment]
🐞 zionbuilder-cli has a bug!

**Comment by zauan** [comment]
@szepeviktor  Why is this a problem? When you push the code, there is a git hook pre-commit action that will make the translation file

**Comment by szepeviktor** [comment]
I see. That is quiet strict.

This PR allows the developer not to update the pot file when there is no change in the strings but they move a few lines lower in the code.

**Comment by szepeviktor** [comment]
it is up to **you** to merge / close this

**Comment by szepeviktor** [comment]
BTW always updating the pot file may disturb you in the future

**Comment by szepeviktor** [comment]
@zauan CI fails as it generates `languages/Zionbuilder.pot` 

please see https://github.com/zionbuilder/zionbuilder-cli/pull/7

**Comment by szepeviktor** [comment]
> You are right as always

I was wrong: it failed because my shell code.
But currently it is not able to detect missing translations because of https://github.com/zionbuilder/zionbuilder-cli/pull/7

**Pull request merged**
