### PR TITLE
add link to zion admin

### PR DESCRIPTION
**Pull request by raluseru**
https://hogash.atlassian.net/browse/ZB-1563

### CODE REVIEW

**Comment by szepeviktor** [comment]
POEdit make a bit different pot file than WP-CLI

```diff
diff --git a/languages/zionbuilder.pot b/languages/zionbuilder.pot
index 9f0e42e..21cff47 100644
--- a/languages/zionbuilder.pot
+++ b/languages/zionbuilder.pot
@@ -1,4034 +1,4340 @@
-# Copyright (C) 2020 Zionbuilder
-# This file is distributed under the same license as the Zionbuilder package.
+# Copyright (C) 2020 zionbuilder.io
+# This file is distributed under the same license as the ZionBuilder plugin.
 msgid ""
 msgstr ""
-"Project-Id-Version: Zionbuilder\n"
+"Project-Id-Version: Zionbuilder 1.0.0\n"
+"Report-Msgid-Bugs-To: https://github.com/zionbuilder/zionbuilder/issues/new/choose\n"
+"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
+"Language-Team: ZionBuilder <hello@zionbuilder.io>\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
-"Language-Team: <hello@hogash.com> Hogash\n"
-"X-Poedit-Basepath: ..\n"
-"X-Poedit-KeywordsList: __;_e;_ex:1,2c;_n:1,2;_n_noop:1,2;_nx:1,2,4c;_nx_noop:1,2,3c;_x:1,2c;esc_attr__;esc_attr_e;esc_attr_x:1,2c;esc_html__;esc_html_e;esc_html_x:1,2c\n"
-"X-Poedit-SearchPath-0: .\n"
```

Please see https://github.com/zionbuilder/zionbuilder/blob/master/.github/workflows/test.yml#L31-L34

**Comment by szepeviktor** [comment]
WP-CLI is beneficial as it can be run on the command line - no need for a GUI.

**Comment by raluseru** [comment]
Hi, I still get error if I ran that command line

**Comment by szepeviktor** [comment]
See the commit, the command and the test result in #44

**Pull request merged**
