### PR TITLE
1.0.1 Fixes and features

### PR DESCRIPTION
**Pull request by zauan**
Implemented upgrade system

### CODE REVIEW

**Comment by szepeviktor** [comment]
🤖: _Out of memory!_
🤖: _Unable to process changes._

**Comment by szepeviktor** [comment]
You could store CSS rules in a structure
e.g.

```php
$css_rules = [
    // Selector
    '.data, #head' => [
        // Propery  => Value
        'flex-wrap' => 'none',
        'justify-content' => 'space-around',
    ],
    'section, .wrapper' => [
        // Or even multiple values
        'background' => ['url("an/image.jpg")', 'url("an/image.jpg")'],
    ],
];
```

**Comment by szepeviktor** [comment]
kép

What a nice output!

**Comment by zauan** [comment]
> You could store CSS rules in a structure
> e.g.
> 
> ```
> $css_rules = [
>     // Selector
>     '.data, #head' => [
>         // Propery  => Value
>         'flex-wrap' => 'none',
>         'justify-content' => 'space-around',
>     ],
>     'section, .wrapper' => [
>         // Or even multiple values
>         'background' => ['url("an/image.jpg")', 'url("an/image.jpg")'],
>     ],
> ];
> ```
> 
> This is PHP but similarly in JavaScript.
> There must be an npm package for this.

The builder allows you to modify the CSS for an infinite combination of responsive device and states ( hover, focus, before, after, etc ). We store the css rules as:

```
$css = [
	'selector_id' => [ // fe. .my-class
		'device_id' => [ // fe. mobile
			'selector_state' => [ // fe. hover
				'flex-direction' => 'column' // CSS rule
			]
		]
	]
];
```
This allows us to put green bullets to options that are modified, so you can easily see what options are modified for an element

**Comment by zauan** [comment]
> kép
> 
> What a nice output!

Yep, really nice :)

**Comment by szepeviktor** [comment]
> We store the css rules as

Then why are there so many string manipulations in Style class?

https://github.com/zionbuilder/zionbuilder/pull/56/files#diff-e4dcaf8ff493b49bfb115e8607f6e017

**Pull request merged**
